### ISSUE TITLE
Clashing React Version numbers

### ISSUE THREAD

**Issue by OSHistory** [boundlessgeo/sdk-generator#2]
Running the web-sdk command and installing the node modules leaves one with two clashing react versions, resulting in a "addComponentAsRefTo(...)" error and non-rendering of the Map. This is confirmed by the output of: 
~~~
npm ls react
foobar@0.0.0 /tmp/foobar
├─┬ boundless-sdk@0.9.13
│ └── react@15.4.0 
└── react@15.3.2 
~~~

Removing the React dependency from the *boundless-web-sdk* module and setting the react dependency to the same version as in the main package.json (15.3.2.) fixes the problem. 

BTW: After I got it working I started the tutorial... Great work on the sdk! 

Output of my configuration: 

~~~
web-sdk -V 
0.9.5

node -v 
v6.0.0

npm -v 
3.8.6

nvm --version
0.32.1
~~~

~~~

**Comment by bartvde** [comment]
Sorry for the late reply, should be resolved by now.
